"""Initial migration

Revision ID: 1ad30fbe84ef
Revises: 
Create Date: 2025-10-17 14:10:16.059627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad30fbe84ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('questions',
    sa.Column('original_xls_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty'), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('option_a', sa.Text(), nullable=False),
    sa.Column('option_b', sa.Text(), nullable=False),
    sa.Column('option_c', sa.Text(), nullable=False),
    sa.Column('option_d', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_questions_created_at', 'questions', ['created_at'], unique=False)
    op.create_index('idx_questions_topic_difficulty', 'questions', ['topic', 'difficulty'], unique=False)
    op.create_index(op.f('ix_questions_difficulty'), 'questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_original_xls_id'), 'questions', ['original_xls_id'], unique=False)
    op.create_index(op.f('ix_questions_topic'), 'questions', ['topic'], unique=False)
    op.create_table('quiz_sessions',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('quiz_definition', sa.JSON(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'FINISHED', 'EXPIRED', 'ABANDONED', name='sessionstatus'), nullable=False),
    sa.Column('current_question_index', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quiz_sessions_expires_at', 'quiz_sessions', ['expires_at'], unique=False)
    op.create_index('idx_quiz_sessions_started_at', 'quiz_sessions', ['started_at'], unique=False)
    op.create_index('idx_quiz_sessions_status', 'quiz_sessions', ['status'], unique=False)
    op.create_index('idx_quiz_sessions_user_id', 'quiz_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_quiz_sessions_id'), 'quiz_sessions', ['id'], unique=False)
    op.create_table('answers',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('correct_option', sa.Enum('A', 'B', 'C', 'D', name='correctoption'), nullable=False),
    sa.Column('correct_text', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_index(op.f('ix_answers_id'), 'answers', ['id'], unique=False)
    op.create_table('leaderboard',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_leaderboard_created_at', 'leaderboard', ['created_at'], unique=False)
    op.create_index('idx_leaderboard_percentage', 'leaderboard', ['percentage'], unique=False)
    op.create_index('idx_leaderboard_score', 'leaderboard', ['score'], unique=False)
    op.create_index('idx_leaderboard_topic', 'leaderboard', ['topic'], unique=False)
    op.create_index('idx_leaderboard_topic_score', 'leaderboard', ['topic', 'score'], unique=False)
    op.create_index(op.f('ix_leaderboard_id'), 'leaderboard', ['id'], unique=False)
    op.create_table('session_answers',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_option', sa.String(length=1), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_taken_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_answers_created_at', 'session_answers', ['created_at'], unique=False)
    op.create_index('idx_session_answers_question_id', 'session_answers', ['question_id'], unique=False)
    op.create_index('idx_session_answers_session_id', 'session_answers', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_answers_id'), 'session_answers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_answers_id'), table_name='session_answers')
    op.drop_index('idx_session_answers_session_id', table_name='session_answers')
    op.drop_index('idx_session_answers_question_id', table_name='session_answers')
    op.drop_index('idx_session_answers_created_at', table_name='session_answers')
    op.drop_table('session_answers')
    op.drop_index(op.f('ix_leaderboard_id'), table_name='leaderboard')
    op.drop_index('idx_leaderboard_topic_score', table_name='leaderboard')
    op.drop_index('idx_leaderboard_topic', table_name='leaderboard')
    op.drop_index('idx_leaderboard_score', table_name='leaderboard')
    op.drop_index('idx_leaderboard_percentage', table_name='leaderboard')
    op.drop_index('idx_leaderboard_created_at', table_name='leaderboard')
    op.drop_table('leaderboard')
    op.drop_index(op.f('ix_answers_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_quiz_sessions_id'), table_name='quiz_sessions')
    op.drop_index('idx_quiz_sessions_user_id', table_name='quiz_sessions')
    op.drop_index('idx_quiz_sessions_status', table_name='quiz_sessions')
    op.drop_index('idx_quiz_sessions_started_at', table_name='quiz_sessions')
    op.drop_index('idx_quiz_sessions_expires_at', table_name='quiz_sessions')
    op.drop_table('quiz_sessions')
    op.drop_index(op.f('ix_questions_topic'), table_name='questions')
    op.drop_index(op.f('ix_questions_original_xls_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_difficulty'), table_name='questions')
    op.drop_index('idx_questions_topic_difficulty', table_name='questions')
    op.drop_index('idx_questions_created_at', table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###